# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kjhCcDVUKsaBzfjMBPfZe73Br4bVQO0M
"""

import pandas as pd
from sklearn.tree import DecisionTreeClassifier

datos = pd.read_csv('entradas.csv')
datos



X= datos.drop(columns = 'edad')
y=datos['precio_entrada']
modelo = DecisionTreeClassifier()
modelo.fit(X,y)
modelo

prediccion = modelo.predict([[61,100]])
prediccion